"""Baseline PER-SITO del gate blind-except (#224) — dati, non logica.

Ogni voce è `(funzione, motivo)` dove il motivo viene dal `# noqa: BLE001` **sulla
riga dell'except**, normalizzato (minuscolo, spazi collassati) e preso PER INTERO: troncarlo farebbe collidere due motivi con lo stesso prefisso, e la sostituzione a saldo zero ripasserebbe.

Prima della #224 il gate confrontava solo il NUMERO di blind-except per file, quindi
rimuoverne uno motivato e aggiungerne uno nudo altrove nello stesso file lasciava il
totale invariato e passava. Con le identità qui sotto quella sostituzione a saldo zero
non passa più.

**Come si aggiorna:** `python tools/gen_blind_except_sites.py` e si LEGGE il diff.
Un baseline aggiornato a occhi chiusi è peggio di nessun baseline — vedi il commento
in testa a `test_blind_except_allowlist.py`.
"""

# file → tuple ordinate di (funzione, motivo normalizzato)
SITI = {
    'license_manager/core.py': (
        ('_persist_key_file', 'cleanup del temporaneo su qualsiasi errore, anche keyboardinterrupt/systemexit, e poi rilancia: il seed privato non deve restare in un .tmp orfano a permessi non garantiti'),
        ('_persist_key_file', "create fallita a meta': rimuove il file parziale appena creato e rilancia. non c'era una chiave prima (o_excl), quindi non si distrugge nulla di irrecuperabile"),
    ),
    'license_manager/gui.py': (
        ('LicenseManagerApp.__init__', 'headless/senza window manager: best-effort'),
        ('LicenseManagerApp._auto_backup_safe', 'il backup non deve poter far fallire emissione/revoca'),
        ('LicenseManagerApp._build_ui', 'headless/tk assente: la gui non è il gate'),
        ('LicenseManagerApp._cancel_publish_tick', 'id scaduto/invalido: ininfluente'),
        ('LicenseManagerApp._check_access_async', 'thread non avviabile: libera il flag e segnala'),
        ('LicenseManagerApp._check_access_worker', 'finestra distrutta: nessuna ui da aggiornare'),
        ('LicenseManagerApp._check_access_worker', 'il thread non deve morire in silenzio'),
        ('LicenseManagerApp._conferma', 'dialog tk best-effort, fail-closed'),
        ('LicenseManagerApp._copia_negli_appunti', 'clipboard assente/occupata'),
        ('LicenseManagerApp._evaluate_delete', 'la vista della revoca non è il gate: qui'),
        ('LicenseManagerApp._evaluate_renew', 'stato ignoto: si ferma, non si chiede'),
        ('LicenseManagerApp._on_close', 'finestra già distrutta: best-effort'),
        ('LicenseManagerApp._on_export', 'dialog tk best-effort'),
        ('LicenseManagerApp._on_export_backup', 'dialog tk best-effort'),
        ('LicenseManagerApp._on_issue', 'render tk best-effort'),
        ('LicenseManagerApp._on_publish_revocation', 'dialog tk best-effort'),
        ('LicenseManagerApp._on_registry_refresh', 'vista registro best-effort (fetch + render)'),
        ('LicenseManagerApp._on_registry_select', 'selezione best-effort, non deve mai sollevare'),
        ('LicenseManagerApp._on_restore_backup', 'dialog tk best-effort'),
        ('LicenseManagerApp._on_save_publish_settings', 'widget headless/distrutto: best-effort'),
        ('LicenseManagerApp._propaga_revoca', 'config illeggibile: non si tace, si avvisa'),
        ('LicenseManagerApp._propaga_revoca', 'vedi «non solleva mai» nel docstring'),
        ('LicenseManagerApp._publish_async', 'thread non avviabile: libera il flag e segnala'),
        ('LicenseManagerApp._publish_tick', 'il ciclo non deve morire per un errore imprevisto'),
        ('LicenseManagerApp._publish_worker', 'finestra distrutta: nessuna ui da aggiornare'),
        ('LicenseManagerApp._publish_worker', 'il thread non deve morire in silenzio'),
        ('LicenseManagerApp._read', 'lettura tk best-effort'),
        ('LicenseManagerApp._refresh_key_state', 'render tk best-effort'),
        ('LicenseManagerApp._refresh_publish_fields', 'precompilazione best-effort (headless/widget assenti)'),
        ('LicenseManagerApp._refresh_publish_status', 'render tk best-effort, come `_set_msg`'),
        ('LicenseManagerApp._revoked_serials', 'vista best-effort; il gate passa `strict=true`'),
        ('LicenseManagerApp._schedule_publish_tick', 'finestra distrutta/headless: niente ri-arm'),
        ('LicenseManagerApp._schedule_publish_tick', 'finestra distrutta/headless: niente ri-arm'),
        ('LicenseManagerApp._schedule_publish_tick', 'finestra distrutta/headless: niente ri-arm'),
        ('LicenseManagerApp._schedule_publish_tick', 'impostazioni illeggibili: cadenza di default'),
        ('LicenseManagerApp._set_msg', 'render tk best-effort'),
        ('LicenseManagerApp._show_token', 'render tk best-effort'),
        ('LicenseManagerApp._stila_tabella', 'lo stile è cosmetico: se fallisce la tabella resta usabile'),
        ('LicenseManagerApp._testo_widget', 'lettura tk best-effort'),
    ),
    'license_manager/log_safe.py': (
        ('RedazioneFilter.filter', 'args incoerenti: meglio il grezzo che nessun log'),
        ('RedazioneFilter.filter', 'mai far cadere una chiamata di log'),
        ('RedazioneFilter.filter', 'traceback non formattabile: si dice, non si perde'),
    ),
    'license_manager/publish_store.py': (
        ('_keyring', 'dipendenza opzionale assente/rotta: fallback pulito'),
        ('delete_publish_token', 'voce assente o backend giù: nulla da rimuovere'),
        ('keyring_available', 'backend `fail`/non configurato → non disponibile'),
        ('load_publish_token', 'lettura fallita = come assente (mai crash)'),
        ('save_publish_token', 'backend non disponibile: il chiamante avvisa'),
    ),
    'license_manager/publisher.py': (
        ('_rimuovi_file_di_prova', 'pulizia best-effort: mai un crash, si dice e basta'),
        ('check_access', 'rete a metà verifica: si dichiara ciò che si sa'),
        ('check_access', 'rete instabile a metà verifica: si dichiara ciò che si sa'),
        ('check_access', 'rete: esito strutturato, mai crash'),
        ('check_access', 'rete: esito strutturato, mai crash'),
        ('get_file_sha', 'qualunque problema di rete: esito strutturato, mai crash'),
        ('publish', 'rete: esito strutturato, mai crash'),
    ),
    'license_manager/registry.py': (
        ('remove_record', 'cleanup del temporaneo su qualsiasi errore, anche keyboardinterrupt/systemexit, e poi rilancia: il registro vecchio resta intatto, mai un .tmp orfano accanto'),
    ),
    'tests/conftest.py': (
        ('_verifica_nessuno_shadowing_di_tests._dove_risolve_tests', 'diagnostica: non deve mai mascherare'),
    ),
    'tests/integration/test_app_runtime_glue.py': (
        ('_avvia_e_raccogli', "`_start` muore piu' avanti (nessun listener reale)"),
    ),
    'tests/integration/test_reconnect_110.py': (
        ('_start_fino_al_bump', "`_start` muore piu' avanti (nessun telegram reale)"),
        ('_transient_exc', 'firma costruttore diversa → senza messaggio'),
    ),
    'tests/integration/test_resilience_109.py': (
        ('test_expire_tick_vs_process_concorrenti_non_corrompono_csv._expirer', 'registra per assert, non nascondere'),
        ('test_expire_tick_vs_process_concorrenti_non_corrompono_csv._producer', 'registra per assert, non nascondere'),
    ),
    'tests/safety/test_csv_atomic.py': (
        ('test_clear_e_write_concorrenti_non_corrompono.clearer_t', "raccolto per l'assert"),
        ('test_clear_e_write_concorrenti_non_corrompono.writer_t', "raccolto per l'assert"),
        ('test_concorrenza_write_clear_non_corrompe.clear_loop', "raccolto per l'assert"),
        ('test_concorrenza_write_clear_non_corrompe.writer_loop', "raccolto per l'assert"),
        ('test_stress_write_clear_500_iterazioni_non_corrompe.clear_loop', "raccolto per l'assert"),
        ('test_stress_write_clear_500_iterazioni_non_corrompe.writer_loop', "raccolto per l'assert"),
    ),
    'tests/safety/test_redazione_seed_205.py': (
        ('_funzione_del_workflow', 'supporto opzionale, non deve rompere'),
    ),
    'tests/unit/test_betfair_local_db.py': (
        ('test_scrittura_concorrente_aspetta_il_lock_e_non_fallisce._writer', "raccolto per l'assert"),
    ),
    'tests/unit/test_chatid_dispatcher_137.py': (
        ('test_anche_gli_altri_builder_hanno_il_default_sola_lettura', 'qui interessa solo come legge la config'),
    ),
    'tests/unit/test_parser_file_avvelenato_b9.py': (
        ('test_fuzz_strutturale_nessuna_classe_inattesa', 'è ciò che si sta misurando'),
        ('test_il_veleno_e_davvero_veleno', 'è esattamente ciò che si misura'),
    ),
    'tests/unit/test_reconnect_policy.py': (
        ('test_real_transient_types_non_solleva_ed_e_cache', "sonda d'ambiente: `telegram.error` non importabile e' uno dei due casi attesi, non un errore del test — decide quale asserzione applicare"),
    ),
    'tests/unit/test_store_temps_warn_dedup_76.py': (
        ('test_warn_concorrente_sotto_lock._spara', "registra per l'assert `errori == []`: un thread che muore in silenzio farebbe passare il test senza aver misurato la contesa"),
    ),
    'xtrader_bridge/app.py': (
        ('App._apply_license_lock', 'best-effort'),
        ('App._apply_license_lock', 'best-effort'),
        ('App._betfair_competitions', 'best-effort: db assente/illeggibile → nessuna competizione'),
        ('App._betfair_id_resolver', 'best-effort: il flusso non deve crashare'),
        ('App._betfair_teams_for_competition', 'best-effort: db assente/illeggibile → nessuna squadra'),
        ('App._build_ui', 'pannello assistente best-effort: mai rompere la gui'),
        ('App._cancel_pending_autostart', 'id già scaduto/invalid: ininfluente'),
        ('App._chiudi_finestre_operative_per_lock', 'già distrutta/tcl giù: il lock non deve rompersi'),
        ('App._config_summary_snapshot', 'db occupato/assente: fail-soft'),
        ('App._confirm_collaudo_mode', 'su errore dialog → non confermare'),
        ('App._confirm_multi_signal', 'su errore dialog → non confermare'),
        ('App._confirm_real_mode', 'su qualsiasi errore dialog → non confermare'),
        ('App._copy_diagnostics', 'clipboard tk indisponibile/rifiutata -> esito a log, mai crash della finestra'),
        ('App._delete_betfair_team', 'best-effort: db assente/illeggibile → non eliminato'),
        ('App._dictionary_viewer_controller', 'best-effort: degrada a none, niente crash gui'),
        ('App._expire_tick', 'esito riportato a log, no crash'),
        ('App._export_real_audit', 'esito a log, no crash'),
        ('App._journal', 's110 — il journal è diagnostico: un suo errore non deve'),
        ('App._kick_csv_probe_async._worker', 'sonda salute best-effort (come _refresh_health):'),
        ('App._known_betfair_teams', 'best-effort: db assente/illeggibile → nessun nome'),
        ('App._known_market_terms', 'best-effort: db assente/illeggibile → liste vuote'),
        ('App._language_chosen', 'chiusura best-effort del selettore (widget già distrutto)'),
        ('App._license_bloccata_da_revoca', 'la diagnosi del perché non deve rompere il lock'),
        ('App._license_is_valid', 'errore imprevisto nel calcolo stato → fail-closed'),
        ('App._license_tick', 'un errore del gate non deve fermare il tick'),
        ('App._maybe_open_language_selector', 'gui best-effort: senza scelta resta it e si ripropone al prossimo avvio'),
        ('App._mostra_license_banner', 'render tk best-effort: il banner non può rompere il lock'),
        ('App._notify_already_running', "headless/display assente: l'uscita avviene comunque"),
        ('App._on_close', 'id già scaduto/invalido: best-effort'),
        ('App._on_close', 'id già scaduto/invalido: best-effort'),
        ('App._on_close', 'teardown assistente best-effort'),
        ('App._open_log_folder', 'esito a log, no crash'),
        ('App._open_tools', 'widget tk distrutto: tratta come assente'),
        ('App._open_wizard', "focus best-effort: la finestra c'è comunque"),
        ('App._open_wizard', 'gui best-effort: mai crash della finestra'),
        ('App._open_wizard', 'riferimento stantio (tk smontato): si riapre da zero'),
        ('App._process_confirmation', 'esito a log, no crash'),
        ('App._refresh_health', 'il pannello salute è diagnostica best-effort'),
        ('App._refresh_tool_panels_after_profile', 'best-effort, ma non silenzioso'),
        ('App._resync_token_field', 'widget tk distrutto: tratta come assente'),
        ('App._revoca_nega', 'in dubbio non si accusa di revoca (fail-safe)'),
        ('App._revocation_gate_ok', 'la diagnostica non può rompere il fail-open'),
        ('App._revocation_gate_ok', 'un errore imprevisto non deve fermare un utente'),
        ('App._revocation_loop', 'il supervisore non deve morire per un errore imprevisto'),
        ('App._run_bot', 'chiusura best-effort'),
        ('App._run_bot', 'gestito sotto'),
        ('App._safe_shutdown_tg', "teardown best-effort del loop: un errore qui non deve impedire l'azzeramento dell'handle"),
        ('App._safe_shutdown_tg._shutdown', 'chiusura best-effort'),
        ('App._schedule_license_tick', 'finestra distrutta: niente ri-arma'),
        ('App._schedule_stop_clear_retry', 'id già scaduto/invalido: best-effort'),
        ('App._select_tool_tab', 'hub chiuso/distrutto: nessuna ui da spostare'),
        ('App._set_license_banner', 'render tk best-effort'),
        ('App._set_operational_lock', 'widget senza `state`/distrutto: best-effort'),
    ),
    'xtrader_bridge/atomic_io.py': (
        ('atomic_write', 'cleanup del temporaneo su qualsiasi errore, anche keyboardinterrupt/systemexit, e poi rilancia: senza, un .tmp resterebbe orfano sul disco'),
    ),
    'xtrader_bridge/betfair/dictionary_viewer_gui.py': (
        ('DictionaryViewerPanel._apply_tree_style', 'lo stile è cosmetico, mai bloccante'),
        ('DictionaryViewerPanel._refresh', 'lettura best-effort, niente crash gui'),
    ),
    'xtrader_bridge/config_agent.py': (
        ('RealAnthropicClient._ensure', 'soft-import: qualsiasi errore di import = libreria assente -> runtimeerror con messaggio guida'),
        ('ToolRegistry._audit', 'il logging non deve mai far fallire il dispatch'),
        ('ToolRegistry._safe_out', "la seconda rete non deve poter rompere l'assistente"),
        ('ToolRegistry._safe_out', "vedi sotto: la garanzia dev'essere strutturale"),
        ('ToolRegistry.dispatch', "nessun tool deve poter far crashare l'agente"),
        ('_crude_chat_mask', '`__str__` difettoso: non possiamo nemmeno leggere il testo'),
        ('_crude_chat_mask', "iterabile che solleva durante l'iterazione"),
        ('_crude_chat_mask', 'un elemento difettoso non ferma gli altri'),
        ('_dictionary_entries', 'dizionario non incluso/illeggibile: fail-safe (none), mai crash'),
        ('build_health_report', "provider dell'app difettoso: mai crash, ripiega su config"),
        ('build_journal_report', 'risoluzione path (config_dir) difettosa: fail-safe'),
        ('build_message_preview', 'tester sola-lettura: un parser attivo malformato o'),
    ),
    'xtrader_bridge/config_agent_controller.py': (
        ('AgentController._emit', 'un handler della view non deve rompere il controller'),
        ('AgentController._handle_message', 'persistenza best-effort: mai scartare il turno'),
        ('AgentController.apply_pending', 'loader che solleva = config non leggibile ora: fail-safe'),
        ('AgentController.apply_pending', 'save fallito/eccezione: fail-safe (esito negativo, non crash)'),
        ('AgentController.enable', "loader difettoso non deve impedire l'avvio: default it"),
        ('AgentController.redact_for_log', 'config illeggibile: log comunque coi soli secret redatti'),
        ('AgentWorker._process_one', 'un turno fallito non deve uccidere il worker'),
    ),
    'xtrader_bridge/config_agent_gui.py': (
        ('AssistantPanel._append', 'logging best-effort'),
        ('AssistantPanel._hide_pending', 'widget già distrutto (teardown): best-effort'),
        ('AssistantPanel._on_event', 'root tk distrutta / assente (teardown): best-effort'),
    ),
    'xtrader_bridge/config_store.py': (
        ('_default_recognition_mode', 'qualunque errore nel gate → name_only (fail-closed, a10)'),
        ('_save_config_locked', 'rollback best-effort'),
        ('migrate_legacy_config', 'best-effort, ma ora loggato (non silenzioso)'),
    ),
    'xtrader_bridge/config_summary_gui.py': (
        ('ConfigSummaryPanel._render', 'provider best-effort'),
    ),
    'xtrader_bridge/csv_writer.py': (
        ('clear_stale_csv', 'diagnostica best-effort, mai bloccare il return'),
    ),
    'xtrader_bridge/custom_parser_gui.py': (
        ('CustomParserPanel._add_provider', 'config illeggibile o salvataggio fallito -> messaggio nel pannello, mai crash della finestra'),
        ('CustomParserPanel._autoload_active_parser', 'parser attivo illeggibile: editor vuoto'),
        ('CustomParserPanel._builder_snapshot', 'fail-safe: non fotografabile = modificato'),
        ('CustomParserPanel._copy_diag', 'clipboard non disponibile'),
        ('CustomParserPanel._fetch_market_terms', 'best-effort: nessun suggerimento'),
        ('CustomParserPanel._highlight_saved', 'widget distrutto durante un refresh: irrilevante'),
        ('CustomParserPanel._load_market_mapping_profiles', 'fallback sicuro'),
        ('CustomParserPanel._load_name_mapping_profiles', 'fallback sicuro'),
        ('CustomParserPanel._load_providers', 'fallback sicuro'),
        ('CustomParserPanel._mostra_avviso_valore_fisso', 'widget distrutto durante un refresh'),
        ('CustomParserPanel._open_provider_registry', 'navigazione best-effort: mai un crash'),
        ('CustomParserPanel._parser_usage', 'config illeggibile: nessun marcatore, mai un crash'),
        ('CustomParserPanel._preview_id_resolver', 'anteprima sola-lettura: resolver non costruibile -> nessuna anteprima, mai crash del pannello'),
        ('CustomParserPanel._resolve_mapping_profiles', 'fallback sicuro'),
        ('CustomParserPanel._resolve_market_mapping_profiles', 'fallback sicuro'),
        ('CustomParserPanel._resolve_source_language', 'fallback sicuro'),
        ('CustomParserPanel._riga_ha_valore_fisso', 'widget assente/distrutto: nessun gate'),
        ('CustomParserPanel._segui_valore_fisso', 'non legabile: si prova il prossimo'),
        ('CustomParserPanel._segui_valore_fisso', 'variabile non tracciabile: nessun ri-aggancio'),
        ('CustomParserPanel.refresh_options', 'config illeggibile: niente refresh'),
        ('bind_accetta_add', 'firma non ispezionabile: si assume il tk vero'),
    ),
    'xtrader_bridge/custom_pipeline.py': (
        ('_default_registry', 'vedi allowlist blind-except'),
        ('_default_registry', 'vedi allowlist blind-except (p3-14)'),
        ('_resolve_ids_into', 'risoluzione best-effort: niente blocco del flusso'),
    ),
    'xtrader_bridge/dictionary_health.py': (
        ('_conflitti', 'diagnostica: mai bloccare il pannello'),
        ('_solo_profili_esaminati', 'diagnostica: mai bloccare il pannello'),
        ('stato_dizionari', 'diagnostica: mai bloccare il pannello'),
    ),
    'xtrader_bridge/dirty_csv_store.py': (
        ('clear_dirty', 'come sopra'),
        ('dirty_paths', 'registro fail-safe: corrotto/assente = vuoto'),
        ('mark_dirty', 'un i/o rotto non deve bloccare stop/chiusura'),
    ),
    'xtrader_bridge/dizionario.py': (
        ('is_validated', 'assente/header rotto/riga non-dict → non validato (fail-safe)'),
    ),
    'xtrader_bridge/dpi_awareness.py': (
        ('enable_dpi_awareness', "fail-open: l'app parte comunque (solo resa più sfocata)"),
        ('enable_dpi_awareness', "fail-open: senza windll niente dpi, mai bloccare l'avvio"),
        ('enable_dpi_awareness', 'shcore assente (win < 8.1): si prova il fallback'),
    ),
    'xtrader_bridge/gui_utils.py': (
        ('ask_confirm', 'dialog non disponibile: fail-closed, non confermare'),
        ('fit_to_screen', 'finestra non ancora mappata: winfo_screen* solleva -> nessun clamp, dimensioni richieste as-is'),
        ('running_edit_notice', 'una sonda difettosa non deve rompere il salvataggio'),
    ),
    'xtrader_bridge/guided_mapping_gui.py': (
        ('GuidedMappingPanel._load_cfg', 'fallback con messaggio'),
        ('GuidedMappingPanel._load_teams', 'best-effort: db assente/illeggibile → nessuna squadra'),
        ('GuidedMappingPanel._on_sport_change', 'best-effort: db assente/illeggibile → nessuna competizione'),
    ),
    'xtrader_bridge/instance_lock.py': (
        ('acquire', 'backstop fail-open per errori non gestiti nei rami'),
        ('release', 'best-effort: alla terminazione rilascia comunque il so'),
    ),
    'xtrader_bridge/journal_view_gui.py': (
        ('JournalPanel._open_folder', 'best-effort, no crash gui'),
        ('JournalPanel._refresh', 'lettura best-effort, niente crash gui'),
    ),
    'xtrader_bridge/known_teams_gui.py': (
        ('KnownTeamsPanel._on_delete', 'best-effort, niente crash gui'),
        ('KnownTeamsPanel._refresh', 'best-effort, niente crash gui'),
    ),
    'xtrader_bridge/license_gui.py': (
        ('LicensePanel._copy_hardware_id', 'clipboard best-effort: non deve rompere la finestra'),
        ('LicensePanel._evaluate_activation', 'persistenza fallita (disco/permessi): attivazione'),
        ('LicensePanel._read_entry', 'entry non disponibile (headless/teardown)'),
        ('LicensePanel._revoca_nega', 'in dubbio non si accusa di revoca'),
        ('LicensePanel.current_status', 'heartbeat: tollera i transitori, fail-closed'),
        ('LicensePanel.current_status', 'provider difettoso: non determinabile → neutro'),
        ('LicensePanel.refresh_options', 'render tk best-effort'),
    ),
    'xtrader_bridge/license_store.py': (
        ('clear_license', 'rimozione best-effort'),
        ('load_license', 'json/schema corrotto: backup poi fail-safe «nessuna licenza»'),
    ),
    'xtrader_bridge/licensing/ed25519.py': (
        ('verify', 'verifica fail-closed: qualunque errore = firma non valida'),
    ),
    'xtrader_bridge/licensing/hwid.py': (
        ('_mac_component', 'sorgente best-effort: assente = omessa'),
        ('_windows_machine_guid', 'assente/non leggibile = omesso'),
        ('_windows_volume_serial', 'assente = omesso'),
    ),
    'xtrader_bridge/licensing/license.py': (
        ('_b64u_canonico', 'non decodificabile = non canonico (fail-closed)'),
        ('verify_license', 'chiave pubblica malformata: rifiuta tutto (fail-closed)'),
        ('verify_license', 'token corrotto/incompleto: fail-closed'),
    ),
    'xtrader_bridge/licensing/revocation.py': (
        ('verify_revocation_list', 'chiave pubblica malformata: rifiuta (fail-closed)'),
        ('verify_revocation_list', 'lista corrotta/incompleta: fail-closed'),
        ('verify_revocation_list', 'payload non conforme: fail-closed'),
    ),
    'xtrader_bridge/licensing/revocation_client.py': (
        ('fetch_signed', 'qualunque problema di fetch: fail-closed → none'),
    ),
    'xtrader_bridge/name_mapping_gui.py': (
        ('MarketMappingPanel._build_ui', 'variabile non tracciabile: nessuna evidenziazione viva'),
        ('MarketMappingPanel._delete_profile', "l'avviso è best-effort"),
        ('MarketMappingPanel._load_cfg', 'fallback con messaggio'),
        ('MarketMappingPanel._profile_usage', 'parser illeggibili: nessun badge, mai un crash'),
        ('MarketMappingPanel._rename_profile', 'il rename config resta valido'),
        ('NameMappingPanel._build_ui', 'variabile non tracciabile: nessuna evidenziazione viva'),
        ('NameMappingPanel._delete_profile', "l'avviso è best-effort"),
        ('NameMappingPanel._load_cfg', 'fallback con messaggio'),
        ('NameMappingPanel._prefill_betfair_names', 'best-effort, niente crash gui'),
        ('NameMappingPanel._profile_usage', 'parser illeggibili: nessun badge, mai un crash'),
        ('NameMappingPanel._rename_profile', 'il rename config resta valido'),
    ),
    'xtrader_bridge/parser_builder.py': (
        ('ParserBuilder.batch_report', 'isolamento per-messaggio (coderabbit'),
    ),
    'xtrader_bridge/provider_gui.py': (
        ('ProviderPanel._add', 'config illeggibile -> messaggio nel pannello e nessuna aggiunta, mai crash della finestra'),
        ('ProviderPanel._load_names', 'fallback sicuro'),
        ('ProviderPanel._provider_usage', 'parser illeggibili: stato ignoto, mai un falso «non usato»'),
        ('ProviderPanel._remove', 'anagrafica gestibile anche senza parser leggibili'),
        ('ProviderPanel._remove', 'config illeggibile -> messaggio nel pannello e nessuna rimozione, mai crash della finestra'),
    ),
    'xtrader_bridge/reconnect_policy.py': (
        ('_real_transient_types', 'telegram assente/incompleto → fallback per nome'),
    ),
    'xtrader_bridge/source_chats_gui.py': (
        ('SourceChatsPanel.refresh_options', 'config illeggibile: niente refresh'),
        ('_ParserListDialog.__init__', 'best-effort (test headless / stub tk)'),
    ),
    'xtrader_bridge/token_store.py': (
        ('_keyring', 'soft-import: qualsiasi errore = keyring non disponibile (dipendenza opzionale), mai propagato'),
        ('available', "probe non distruttivo: il backend 'fail' solleva -> keyring non utilizzabile, si ripiega"),
        ('delete_api_key', 'voce inesistente o backend assente -> niente da rimuovere'),
        ('delete_token', 'voce inesistente (passworddeleteerror) o backend assente -> niente da rimuovere'),
        ('load_api_key_status', "lettura fallita -> read_ok=false, mai confuso con 'chiave assente'"),
        ('load_token_status', "lettura fallita -> read_ok=false, mai confuso con 'token assente': cancellarlo distruggerebbe un token preesistente solo illeggibile"),
        ('save_api_key', 'backend che solleva = chiave non salvata; nessun fallback plaintext, resta assente (fail-safe)'),
        ('save_token', 'backend che solleva = token non salvato -> il chiamante ripiega sul plaintext'),
    ),
    'xtrader_bridge/tools_gui.py': (
        ('ToolsWindow.__init__', 'isolamento per-scheda'),
        ('ToolsWindow._on_tab_change', 'refresh best-effort'),
        ('ToolsWindow.select_tab', 'widget distrutto/titolo invalido: resta la scheda corrente'),
    ),
    'xtrader_bridge/ui_cards.py': (
        ('_best_effort', 'widget finto/distrutto: presentazione, mai crash'),
        ('badge', 'font ctk non costruibile (tk non pronto/headless) -> badge senza font, mai crash della vista'),
        ('card', 'doppio di test senza ctkfont funzionante'),
        ('hint', 'font ctk non costruibile (tk non pronto/headless) -> hint senza font, mai crash della vista'),
        ('tune_scrolling', 'accordatura best-effort: mai rompere la costruzione'),
    ),
    'xtrader_bridge/ui_widgets.py': (
        ('evidenzia_profilo', 'widget distrutto durante un refresh'),
        ('rendi_attivabile', 'widget-spia o distrutto: resta cliccabile col mouse'),
    ),
    'xtrader_bridge/wizard.py': (
        ('check_chat', 'sonda: qualsiasi errore → esito sanificato'),
        ('check_csv', 'i/o reale: esito onesto, mai crash del wizard'),
        ('check_token', 'sonda: qualsiasi errore → esito sanificato'),
    ),
    'xtrader_bridge/wizard_gui.py': (
        ('WizardWindow._probe_done', 'interprete tk già smontato: come finestra chiusa'),
        ('WizardWindow._run_async.worker', "fail-closed: solo la classe dell'errore (mai token/url grezzi)"),
        ('WizardWindow._run_async.worker', 'finestra/tk distrutti durante la sonda: niente da aggiornare'),
        ('WizardWindow._run_parser_check', 'fail-closed su tutta la valutazione, mai crash'),
    ),
    'xtrader_bridge/write_path.py': (
        ('commit_signal', 'riportato al chiamante, no crash'),
        ('commit_signals', 'riportato al chiamante, no crash'),
        ('commit_signals._realign_dirty_disk', 'riportato al chiamante, no crash'),
    ),
}
