"""P3-39 audit #76 — constraints pinnate per i job di TEST.

Bug: i job di test installavano `pip install -r requirements-dev.txt` con soli FLOOR
`>=` — una release breaking di una dipendenza (o di una transitiva) upstream faceva
diventare rossi TUTTI i PR insieme, nello stesso momento, senza alcun cambiamento nel
repo. Fix: `requirements-dev.lock` (pin `==` generati con pip-compile su Linux+3.11,
stessa piattaforma dei job ubuntu) usato come constraints (`-c`) in pr-checks,
commit-gate e windows-tests: l'upgrade delle dipendenze diventa un atto deliberato
(rigenerare il lock in un PR dedicato), mai una sorpresa.

Questi test difendono: esistenza/forma del lock, copertura di TUTTE le dipendenze
top-level, coerenza coi floor di sicurezza di `requirements.in`, e il wiring `-c`
nei workflow (regex su testo reale, pattern `test_workflow_pins`)."""

import re
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_WF_DIR = _ROOT / ".github" / "workflows"

# I workflow di test che DEVONO installare con le constraints.
# `merge-simulation.yml` aggiunto per il finding P3-ci2 della #114: girava senza `-c` e
# senza i `.lock` nella cache-key. Era sfuggito proprio perché questa lista non lo
# includeva — il guard esisteva già ed era giusto, semplicemente non guardava lì.
_TEST_WORKFLOWS = ("pr-checks.yml", "commit-gate.yml", "windows-tests.yml",
                   "merge-simulation.yml")

# Il job notturno che builda l'EXE non usa le constraints ma il lock HASHATO: compila un
# artefatto distribuibile, quindi ha bisogno della garanzia più forte (`--require-hashes`),
# non solo di versioni pinnate. Stesso trattamento di `build.yaml` / `build-license-manager`.
_HARD_BUILD_WORKFLOW = "merge-simulation-hard.yml"

# Install di `requirements-dev.txt` SENZA constraints, in qualunque forma. `[\s\\]+` invece di
# `\s+` perché in YAML un comando può essere spezzato con la continuazione `\` (rilievo Fable
# #165): `pip install \` + a capo + `-r requirements-dev.txt` è lo stesso identico difetto
# scritto su due righe, e un guard che non lo vede protegge solo chi non va a capo.
_BARE_INSTALL_RE = re.compile(
    r"pip install[\s\\]+(?:--upgrade[\s\\]+)?-r requirements-dev\.txt"
    r"(?![\s\\]+-c requirements-dev\.lock)[^\n]*")

# La controparte POSITIVA. Anche questa tollera la continuazione `\` (rilievo GPT-5.5 #165):
# prima era un confronto di sottostringa esatta su una riga, quindi un workflow **corretto** ma
# scritto su più righe sarebbe stato bocciato. Un guard che boccia il codice giusto costa quanto
# uno che lascia passare quello sbagliato — spinge a disattivarlo.
_GOOD_INSTALL_RE = re.compile(
    r"pip install[\s\\]+-r requirements-dev\.txt[\s\\]+-c requirements-dev\.lock")


def _lock_pins():
    pins = {}
    for line in (_ROOT / "requirements-dev.lock").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "==" in line:
            name, ver = line.split("==", 1)
            # via l'eventuale environment marker (es. `; sys_platform == 'win32'`):
            # i suoi digit corromperebbero il confronto di versione (CodeRabbit #88).
            ver = ver.split(";", 1)[0]
            pins[name.strip().lower().replace("_", "-")] = ver.strip()
    return pins


def _vtuple(ver):
    return tuple(int(p) for p in re.findall(r"\d+", ver)[:3])


def test_lock_esiste_ed_e_pinnato():
    pins = _lock_pins()
    assert len(pins) >= 10, "requirements-dev.lock: attesi pin == per runtime+test+transitive"
    header = (_ROOT / "requirements-dev.lock").read_text(encoding="utf-8")
    assert "autogenerated by pip-compile" in header, (
        "requirements-dev.lock: deve restare autogenerato (mai editato a mano)")
    assert "--hash" not in header, (
        "requirements-dev.lock: niente hash — è usato come constraints (-c), e pip "
        "rifiuta constraints hashate; il lock hashato resta quello di build")


def test_lock_copre_tutte_le_top_level():
    """Ogni dipendenza top-level di requirements.in e requirements-dev.txt deve avere il
    suo pin: una top-level fuori dal lock resterebbe a floor (proprio il bug P3-39)."""
    pins = _lock_pins()
    top = set()
    for fname in ("requirements.in", "requirements-dev.txt"):
        for line in (_ROOT / fname).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith(("#", "-r")):
                top.add(re.split(r"[><=!\[;]", line)[0].strip().lower().replace("_", "-"))
    missing = top - set(pins)
    assert not missing, f"top-level senza pin nel lock: {sorted(missing)}"


def test_lock_rispetta_i_floor_di_sicurezza():
    """I pin devono soddisfare i FLOOR `>=` di requirements.in E requirements-dev.txt
    (review GPT #88: anche una dipendenza dev può avere un floor di sicurezza) — sono
    vincoli di SICUREZZA: h11>=0.16 esclude una CVE, ptb>=21 esclude h11 vulnerabile:
    un lock rigenerato male che retrocedesse sotto un floor deve fallire qui."""
    pins = _lock_pins()
    floors = {}
    for fname in ("requirements.in", "requirements-dev.txt"):
        for line in (_ROOT / fname).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            # (?:\[...\])? — tollera gli extras (es. `pkg[extra]>=1.0`, CodeRabbit #88)
            m = re.match(r"^([A-Za-z0-9._-]+)(?:\[[^\]]+\])?\s*>=\s*([0-9.]+)", line)
            if m:
                floors[m.group(1).lower().replace("_", "-")] = m.group(2)
    assert floors, "requirements.in: attesi floor >= (vincoli di sicurezza)"
    for name, floor in floors.items():
        assert name in pins, f"{name}: floor di sicurezza senza pin nel lock"
        assert _vtuple(pins[name]) >= _vtuple(floor), (
            f"{name}: pin {pins[name]} sotto il floor di sicurezza >={floor}")


def test_ci_installa_con_le_constraints():
    """Ogni install di requirements-dev.txt nei workflow di test deve avere
    `-c requirements-dev.lock`, e la cache-key deve includere i .lock (senza, un
    lock rigenerato riuserebbe la cache pip stantia)."""
    for name in _TEST_WORKFLOWS:
        text = (_WF_DIR / name).read_text(encoding="utf-8")
        bare = _BARE_INSTALL_RE.findall(text)
        assert not bare, f"{name}: install di requirements-dev.txt SENZA constraints → {bare}"
        assert _GOOD_INSTALL_RE.search(text), (
            f"{name}: nessun install con constraints trovato")
        assert "requirements*.lock" in text, (
            f"{name}: cache-dependency-path senza requirements*.lock")


# ── CI-1 (#114 P2): il job notturno che builda l'EXE ────────────────────────────────────────────
def test_il_job_notturno_builda_da_dipendenze_pinnate_e_hashate():
    """CI-1: `merge-simulation-hard` compila un EXE su windows-latest ogni notte.

    Installava `pip install -r requirements-dev.txt pyinstaller httpx`: nessun lock, nessun
    hash, e `pyinstaller`/`httpx` senza alcun vincolo di versione. Un artefatto distribuibile
    costruito da dipendenze che possono cambiare da sola una notte all'altra — mentre il lock
    hashato per Windows (`requirements-build.lock`, che contiene pyinstaller e httpx) era già
    nel repo ed era già usato da `build.yaml` e `build-license-manager.yaml`.

    Serve la garanzia FORTE (`--require-hashes`), non le sole constraints: qui non si tratta di
    stabilizzare la CI ma di sapere cosa finisce dentro l'eseguibile."""
    text = (_WF_DIR / _HARD_BUILD_WORKFLOW).read_text(encoding="utf-8")

    assert "--require-hashes -r requirements-build.lock" in text, (
        f"{_HARD_BUILD_WORKFLOW}: l'EXE notturno deve essere buildato dal lock HASHATO")

    # Il vecchio install nudo non deve tornare, in nessuna delle sue forme.
    nudi = _BARE_INSTALL_RE.findall(text)
    assert not nudi, (
        f"{_HARD_BUILD_WORKFLOW}: install non pinnato reintrodotto → {nudi}")

    assert "requirements*.lock" in text, (
        f"{_HARD_BUILD_WORKFLOW}: cache-dependency-path senza requirements*.lock — un lock "
        "rigenerato riuserebbe la cache pip stantia")


@pytest.mark.parametrize("riga", [
    "      - run: pip install -r requirements-dev.txt",
    "      - run: pip install -r requirements-dev.txt pyinstaller httpx",
    "      - run: pip install --upgrade -r requirements-dev.txt",
    # Continuazione YAML: lo stesso difetto scritto su due righe (rilievo Fable #165).
    "      - run: pip install \\\n          -r requirements-dev.txt pyinstaller",
    "      - run: pip install --upgrade \\\n          -r requirements-dev.txt",
    # Forma `python -m pip`, usata altrove nel repo (rilievo GPT-5.5 #165): è già coperta
    # perché il pattern aggancia la sottostringa `pip install`, ma senza un test la
    # copertura resterebbe accidentale — e la prossima riscrittura potrebbe perderla.
    "      - run: python -m pip install -r requirements-dev.txt",
    "      - run: python -m pip install \\\n          -r requirements-dev.txt",
])
def test_il_guard_riconosce_tutte_le_forme_dell_install_nudo(riga):
    """Il guard è a sua volta testato, perché una regex che non morde è indistinguibile da
    un repository sano.

    Prima di questo giro il pattern pretendeva tutto su una riga: bastava spezzare il comando
    con un `\\` per reintrodurre l'install non pinnato passando i controlli."""
    assert _BARE_INSTALL_RE.search(riga), f"forma non intercettata: {riga!r}"


@pytest.mark.parametrize("riga", [
    "      - run: pip install -r requirements-dev.txt -c requirements-dev.lock",
    "      - run: pip install \\\n          -r requirements-dev.txt \\\n          -c requirements-dev.lock",
    "      - run: python -m pip install --require-hashes -r requirements-build.lock",
])
def test_il_guard_non_segnala_gli_install_corretti(riga):
    """L'altra metà: un guard che grida su tutto viene disattivato entro una settimana."""
    assert not _BARE_INSTALL_RE.search(riga), f"falso positivo su: {riga!r}"


@pytest.mark.parametrize("riga", [
    "      - run: pip install -r requirements-dev.txt -c requirements-dev.lock",
    "      - run: pip install \\\n          -r requirements-dev.txt \\\n          -c requirements-dev.lock",
    "      - run: python -m pip install -r requirements-dev.txt -c requirements-dev.lock",
])
def test_il_check_positivo_accetta_anche_le_forme_spezzate(riga):
    """Rilievo GPT-5.5 (#165): il riconoscimento dell'install CORRETTO era un confronto di
    sottostringa esatta su una riga sola, quindi un workflow sicuro ma scritto su più righe
    veniva bocciato. Un guard che boccia il codice giusto costa quanto uno che lascia passare
    quello sbagliato: entrambi finiscono per essere disattivati."""
    assert _GOOD_INSTALL_RE.search(riga), f"forma corretta non riconosciuta: {riga!r}"


def test_il_lock_di_build_copre_davvero_pyinstaller_e_httpx():
    """Il fix regge solo se il lock contiene ciò che l'install nudo aggiungeva a mano.

    Se una rigenerazione futura togliesse `pyinstaller` da `requirements-build.lock`, il job
    notturno fallirebbe all'improvviso in fase di build — e il motivo (una riga sparita da un
    file autogenerato) sarebbe tutt'altro che ovvio a chi guarda il log."""
    lock = (_ROOT / "requirements-build.lock").read_text(encoding="utf-8")
    for pkg in ("pyinstaller", "httpx", "pytest"):
        assert re.search(rf"(?mi)^{pkg}==", lock), (
            f"requirements-build.lock: manca il pin di {pkg}, che il job notturno usa")
    assert "--hash=" in lock, (
        "requirements-build.lock deve restare hashato: senza hash `--require-hashes` fallisce")
