"""P3-39 audit #76 — constraints pinnate per i job di TEST.

Bug: i job di test installavano `pip install -r requirements-dev.txt` con soli FLOOR
`>=` — una release breaking di una dipendenza (o di una transitiva) upstream faceva
diventare rossi TUTTI i PR insieme, nello stesso momento, senza alcun cambiamento nel
repo. Fix: `requirements-dev.lock` (pin `==` generati con pip-compile su Linux+3.11,
stessa piattaforma dei job ubuntu) usato come constraints (`-c`) in pr-checks,
commit-gate e windows-tests: l'upgrade delle dipendenze diventa un atto deliberato
(rigenerare il lock in un PR dedicato), mai una sorpresa.

Questi test difendono: esistenza/forma del lock, copertura di TUTTE le dipendenze
top-level, coerenza coi floor di sicurezza di `requirements.in`, e il wiring `-c`
nei workflow (regex su testo reale, pattern `test_workflow_pins`)."""

import re
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
_WF_DIR = _ROOT / ".github" / "workflows"

# I workflow di test che DEVONO installare con le constraints.
_TEST_WORKFLOWS = ("pr-checks.yml", "commit-gate.yml", "windows-tests.yml")


def _lock_pins():
    pins = {}
    for line in (_ROOT / "requirements-dev.lock").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "==" in line:
            name, ver = line.split("==", 1)
            pins[name.strip().lower().replace("_", "-")] = ver.strip()
    return pins


def _vtuple(ver):
    return tuple(int(p) for p in re.findall(r"\d+", ver)[:3])


def test_lock_esiste_ed_e_pinnato():
    pins = _lock_pins()
    assert len(pins) >= 10, "requirements-dev.lock: attesi pin == per runtime+test+transitive"
    header = (_ROOT / "requirements-dev.lock").read_text(encoding="utf-8")
    assert "autogenerated by pip-compile" in header, (
        "requirements-dev.lock: deve restare autogenerato (mai editato a mano)")
    assert "--hash" not in header, (
        "requirements-dev.lock: niente hash — è usato come constraints (-c), e pip "
        "rifiuta constraints hashate; il lock hashato resta quello di build")


def test_lock_copre_tutte_le_top_level():
    """Ogni dipendenza top-level di requirements.in e requirements-dev.txt deve avere il
    suo pin: una top-level fuori dal lock resterebbe a floor (proprio il bug P3-39)."""
    pins = _lock_pins()
    top = set()
    for fname in ("requirements.in", "requirements-dev.txt"):
        for line in (_ROOT / fname).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith(("#", "-r")):
                top.add(re.split(r"[><=!\[;]", line)[0].strip().lower().replace("_", "-"))
    missing = top - set(pins)
    assert not missing, f"top-level senza pin nel lock: {sorted(missing)}"


def test_lock_rispetta_i_floor_di_sicurezza():
    """I pin devono soddisfare i FLOOR `>=` di requirements.in (sono vincoli di
    SICUREZZA: h11>=0.16 esclude una CVE, ptb>=21 esclude h11 vulnerabile, ecc.):
    un lock rigenerato male che retrocedesse sotto un floor deve fallire qui."""
    pins = _lock_pins()
    floors = {}
    for line in (_ROOT / "requirements.in").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        m = re.match(r"^([A-Za-z0-9._-]+)\s*>=\s*([0-9.]+)", line)
        if m:
            floors[m.group(1).lower().replace("_", "-")] = m.group(2)
    assert floors, "requirements.in: attesi floor >= (vincoli di sicurezza)"
    for name, floor in floors.items():
        assert name in pins, f"{name}: floor di sicurezza senza pin nel lock"
        assert _vtuple(pins[name]) >= _vtuple(floor), (
            f"{name}: pin {pins[name]} sotto il floor di sicurezza >={floor}")


def test_ci_installa_con_le_constraints():
    """Ogni install di requirements-dev.txt nei workflow di test deve avere
    `-c requirements-dev.lock`, e la cache-key deve includere i .lock (senza, un
    lock rigenerato riuserebbe la cache pip stantia)."""
    for name in _TEST_WORKFLOWS:
        text = (_WF_DIR / name).read_text(encoding="utf-8")
        bare = re.findall(r"pip install -r requirements-dev\.txt(?! -c requirements-dev\.lock)",
                          text)
        assert not bare, f"{name}: install di requirements-dev.txt SENZA constraints"
        assert "pip install -r requirements-dev.txt -c requirements-dev.lock" in text, (
            f"{name}: nessun install con constraints trovato")
        assert "requirements*.lock" in text, (
            f"{name}: cache-dependency-path senza requirements*.lock")
